// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq-BrBkf1eVkUHO3hYlWNRLLhQ9zaQRnA',
    appId: '1:495092528687:web:d916fecbe4e28c001c78da',
    messagingSenderId: '495092528687',
    projectId: 'ai-news-aggregator-460410',
    authDomain: 'ai-news-aggregator-460410.firebaseapp.com',
    storageBucket: 'ai-news-aggregator-460410.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxd3V-sgBonC3G4XBuacXHZwQE1UCT1vM',
    appId: '1:495092528687:android:8f9f499818eac3bb1c78da',
    messagingSenderId: '495092528687',
    projectId: 'ai-news-aggregator-460410',
    storageBucket: 'ai-news-aggregator-460410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHnU-ecsfueMXh-vuQPXwtiGD36DRV4I',
    appId: '1:495092528687:ios:76ff5530c5f155561c78da',
    messagingSenderId: '495092528687',
    projectId: 'ai-news-aggregator-460410',
    storageBucket: 'ai-news-aggregator-460410.firebasestorage.app',
    iosBundleId: 'com.example.newsBiteAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqHnU-ecsfueMXh-vuQPXwtiGD36DRV4I',
    appId: '1:495092528687:ios:76ff5530c5f155561c78da',
    messagingSenderId: '495092528687',
    projectId: 'ai-news-aggregator-460410',
    storageBucket: 'ai-news-aggregator-460410.firebasestorage.app',
    iosBundleId: 'com.example.newsBiteAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq-BrBkf1eVkUHO3hYlWNRLLhQ9zaQRnA',
    appId: '1:495092528687:web:ba7440315d040aca1c78da',
    messagingSenderId: '495092528687',
    projectId: 'ai-news-aggregator-460410',
    authDomain: 'ai-news-aggregator-460410.firebaseapp.com',
    storageBucket: 'ai-news-aggregator-460410.firebasestorage.app',
  );

}